name: meal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  image: ^4.2.0
  provider: ^6.1.2
  flutter_markdown: ^0.7.3
  get_it: ^8.0.3
  flutter_animate: ^4.5.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  url_launcher: ^6.3.0
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  html: ^0.15.4
  google_fonts: ^6.2.1
  video_player: ^2.9.5
  table_calendar: ^3.0.9
  google_generative_ai: ^0.4.7
  #modal_progress_hud_nsn: ^0.3.0
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.5.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.0
  #speech_to_text: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AI_MealMingle.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/AI_MealMingle.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/AI_MealMingle.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/AI_MealMingle.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/firstvideo.mp4
    - assets/images/p.png
    - assets/images/
    - assets/
    - assets/images/food_scan.jpg


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: Allan
      fonts:
        - asset: assets/fonts/Allan.ttf
        - asset: assets/fonts/Allan-Bold.ttf
          weight: 700

    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic-Regular.ttf

    - family: MesauringIcon
      fonts:
        - asset: assets/fonts/MesauringIcon.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic_Condensed-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: Allan
      fonts:
        - asset: assets/fonts/Allan.ttf
        - asset: assets/fonts/Allan-Bold.ttf
          weight: 700

    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic-Regular.ttf

    - family: MesauringIcon
      fonts:
        - asset: assets/fonts/MesauringIcon.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic_Condensed-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    